Process Trigger Resiliency
digi-serve/ab_service_appbuilder pull request #18
Opened 2022-12-15 06:51 UTC by nh758

## Problem
If  a request to `process_manager.trigger` times out we retry 5 times. If `process_manager` is up but working slowly this can cause multiple processes to trigger instead of one. If `process_manger` is down we'll log it as an error, but the process won't be triggered. Either way our data can get messed up if process don't run or run multiple times. 

(I saw this after doing a mass update to ~40 records resulting in ~200 processes)

## Solution
1. Add a unique `requestID` to the `jobData`. This allows `process_manager` to handle the case where the process already triggered but was reported as a timeout (see related prs).
2. Implement a Circuit Breaker pattern (https://hackernoon.com/circuit-breakers-in-microservices-els3tv1), with a fallback function, allowing time for `proces_manager` to recover if it's overwhelmed.
3. Queue failed `process_manager.trigger` request and retry until successful. This means no triggers get lost, even if `process_manager` is offline.

### Notes
Will require adding a table `SITE_PENDING_TRIGGER`

### Related PRs
https://github.com/digi-serve/appbuilder_platform_service/pull/47
https://github.com/digi-serve/ab_service_process_manager/pull/37

2022-12-16 08:17 UTC, wongpratan approved these changes

2023-01-04 21:13 UTC, Hiro-Nakamura requested changes
Nicely done!  I like the circuit breaker pattern.

A few small changes and good to go.

2023-01-05 20:16 UTC, Hiro-Nakamura approved these changes
LGTM!

2023-01-05 20:22 UTC, Hiro-Nakamura commented
Do we know what is happening with the failed integration tests?

2023-01-20 06:36 UTC, merged